### ISSUE TITLE
create user login function

### ISSUE THREAD

**Issue by wenboown** [Twilight-Tales/Twilight-Chat#1]
# Goal:
We need to create a database to keep track of user data between logins.
user data includes but not limit to the following tables:
1. username, password, user_id, 
2. chat history (we can use chainlit's session id as the primary key for chat_history), including a timestamp or datetime field.
3. book reading history (many-to-many relationship with chat_history), we will also use this to keep track of the current reading chapter to filling the context in the chatbot prompt. (record book_title and chapter_title and use pid to link them to the book library and chat history table.)
4. book library (create schema and one book first (https://github.com/Twilight-Tales/Twilight-Chat/blob/main/books.txt), we can add more books later.)

# Existing resources:
1. We can start simple with "sqlite3". Then move to postgresql or other db later.

2. The chainlit already have a simple [password authentication](https://docs.chainlit.io/authentication/password) and [user session tracking](https://docs.chainlit.io/concepts/user-session). We should leverage them.
Note: Chainlit's [data persistent](https://docs.chainlit.io/data-persistence/overview) is a paid service that save. But search around, maybe the 

# todos:
1. create a database schema design and review with the group for feedback
2. implement the database and fill initial data for testing.
3. Need to figure out how to customize the chainlit's login page to add a "registration page" for new user signup.
4. For new user's first chat session, we can use a different system prompt to let the chatbot fill out some user profile, like what book genre they like, etc. Then record or suggest the first book and chapter for the user to read. Starting from the next session, we will use that chapter as context to construct the conversation.
5. Let's do this with chainlit (web frontend) first. After we get everything working, we can integrate it with the phone call frontend.

**Comment by wenboown** [comment]
@plumshum check out a new branch to work on the development of this.

**Comment by plumshum** [comment]
https://www.figma.com/file/kW2PxM2c013pkBnDEWmw8C/Twilight-Chat-Backend-%2B-Design?type=design&node-id=1%3A48&mode=design&t=nHSTAgR1wd5C62oA-1

**Comment by wenboown** [comment]
@plumshum The "many-to-many" relationship between `user` and `book library` is not explicit. The `book reading history` table is the manifest of that relationship. i.e., one user can read many books, and one book can be read by many users, and these are all recorded in the reading history.

So your key design should focus on the `book reading history` table. it should contain user_pid and book_pid (maybe also chapter_pid since we are tracking on the chapter level) for each entry. and timestamp to help keep track on the reading order and support finding out the "current reading chapter".

Sorry I was most likely wrong about saying `book reading history` and `chat_history` is  many-to-many relationship. It is probably a one-to-many relationship. i.e., when the user is reading one chapter, he/she can have multiple chat sessions with the AI. But each chat session should only be about a specific chapter, i.e., one entry in the reading history.

**Comment by wenboown** [comment]
Another choice is to let `book reading history` table use `chat_history` pid instead of user_pid. That way we have a linear connections between all the tables. Otherwise we need to implement some code to keep `book reading history` and `chat_history` consistent.

`user` ---(one-to-many)---> `chat_history`  ---(many-to-one)--->`book reading history` ---(many-to-many)--->`book library`

(This schema implicitly enforced a one-to-one relationship between `user` and  `book reading history`.)
