### ISSUE TITLE
Issue with insert chapter and text into database

### ISSUE THREAD

**Issue by plumshum** [Twilight-Tales/Twilight-Chat#8]
Seems like its inserting letter by letter, not section by section in`prepare_db.ipynb` #
![Screenshot 2024-02-26 224119](https://github.com/Twilight-Tales/Twilight-Chat/assets/91917682/2a6dc3fc-1be6-4eb1-8fa2-f006471b6b2d)
![Screenshot 2024-02-26 224129](https://github.com/Twilight-Tales/Twilight-Chat/assets/91917682/39df2704-e071-4349-a506-117e22b18a0d)

**Comment by wenboown** [comment]
the plain txt files don't have page structure. 

Take a look at the notebook I gave you. You might need to do some modifications. But the high level idea is:

1. Find the title of the book from 1st line, which seems to be a consistent rule that we can rely on of all the txt.
2. Find the table of content part of the txt, extract all the chapter title from it.
3. Use the list of the chapter title to "cut" the rest of the txt files into chapters.
4. Save the structured info we got from step 1-3 in to database.

**Comment by plumshum** [comment]
Not the most optimal solution lol
Get all the chapters with the text. Since the chapters number and titles appear twice with the table of contents i just cut the list in half. Will edit the code so that it won't cut the list in half if there isn't a table of contents.
